name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: absl - Configure cache - src
      id: cache-absl-src
      uses: actions/cache@v2
      with:
        path: output/absl
        key: ${{ runner.os }}-absl-src

    - name: absl - Configure cache - bin
      id: cache-absl-bin
      uses: actions/cache@v2
      with:
        path: output/absl-bin
        key: ${{ runner.os }}-absl-bin

    - name: absl - Clone
      if: steps.cache-absl-src.outputs.cache-hit != 'true'
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: abseil/abseil-cpp 
        path: output/absl

    - name: absl - Configure CMake
      if: steps.cache-absl-bin.outputs.cache-hit != 'true'
      run: cmake -B ${{github.workspace}}/output/absl/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/output/absl-bin -DCMAKE_CXX_STANDARD=17 -DCMAKE_POSITION_INDEPENDENT_CODE=ON output/absl

    - name: absl - Build
      if: steps.cache-absl-bin.outputs.cache-hit != 'true'
      run: cmake --build ${{github.workspace}}/output/absl/build

    - name: absl - Install
      if: steps.cache-absl-bin.outputs.cache-hit != 'true'
      run: cmake --install ${{github.workspace}}/output/absl/build

    - name: redis-s2geo - Configure CMake
      run: cmake -B ${{github.workspace}}/output/redis-s2geo/build -DABSL_PATH="${{github.workspace}}/output/absl-bin" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

    - name: redis-s2geo - Build
      run: cmake --build ${{github.workspace}}/output/redis-s2geo/build

    - name: redis-s2geo - Test
      run: ${{github.workspace}}/output/redis-s2geo/build/redis-s2geo-test
